version: '2'
services:
  operand-service:
    image: feelgreat/operand-service
    container_name: operand-service
    entrypoint: ["./dockerize","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8081:8081

  operator-service:
    image: feelgreat/operator-service
    container_name: operator-service
    entrypoint: ["./dockerize","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8082:8082

  calculation-service:
    image: feelgreat/calculation-service
    container_name: calculation-service
    entrypoint: ["./dockerize","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    ports:
      - 8080:8080